make location more clear
uwu/shelter pull request #2
Opened 2022-11-26 23:15 UTC by oscie57

2022-11-26 23:17 UTC, yellowsink requested changes

2022-11-26 23:17 UTC, twnlink requested changes
It appears you didn't add instructions for non-Windows operating systems.

2022-11-26 23:17 UTC, yellowsink commented on README.md
> +- Find your discord install folder (`%LocalAppData%`) and go into `resources/` - if theres a file called `app.asar` youre probably in the right place.
please specify that this only applies to windows

2022-11-27 01:16 UTC, oscie57 commented
i've fixed it

2022-11-27 14:20 UTC, yellowsink approved these changes

2022-11-27 14:20 UTC, merged